- .gitignore
- Cargo.lock
- Cargo.toml
- tesseract-core/src/sql.rs
- tesseract-postgres/Cargo.toml
- tesseract-postgres/README.md
- tesseract-postgres/src/df.rs
- tesseract-postgres/src/lib.rs
- tesseract-server/Cargo.toml
- tesseract-server/src/db_config.rs
Adds basic support for using postgres with tesseract
> Basic Postgres support for tesseract

- Cargo.lock
- tesseract-core/Cargo.toml
- tesseract-core/src/lib.rs
- tesseract-core/src/schema/xml.rs
- Updates `serde-xml-rs` to version 0.3.1
- Adds support for annotations
> Serde XML updates

- Cargo.lock
- tesseract-server/Cargo.toml
- tesseract-server/src/app.rs
- tesseract-server/src/handlers/logic_layer/aggregate.rs
- tesseract-server/src/logic_layer/README.md
- tesseract-server/src/logic_layer/config.rs
- tesseract-server/src/logic_layer/mod.rs
- tesseract-server/src/main.rs
Example config:
```json
{
"aliases": {
"cubes": [
{
"name": "example",
"cube": "Example"
}
]
}
}
```
> Logic layer config file aliasing and docs

- tesseract-server/src/logic_layer/README.md
- tesseract-server/src/logic_layer/cache.rs
> Time support improvements

- Cargo.lock
- tesseract-core/Cargo.toml
- tesseract-core/src/format.rs
new jsonarray format to save some bytes over the wire
Also, added feature preserve_order to serde_json dependency
> [core] jsonarrays format, and preserve_order for json

- tesseract-core/src/lib.rs
- tesseract-server/src/handlers/logic_layer/shared.rs
Removes duplicated check on caption resolution.
> [logic layer] Caption Resolution Fix

- tesseract-clickhouse/src/sql/growth.rs
- tesseract-core/src/query_ir.rs
> fix growth calculation when starting with neg value

- tesseract-core/src/lib.rs
pushing this through in a little bit of a hurry, but should be easy to revert if necessary, it's only one file.
> [core] allow specifying caption for parent

- conditional-cut.txt
- tesseract-clickhouse/src/sql/conditional_cut.rs
> [core] cond. cut notes and lay out sql

- Cargo.lock
- tesseract-core/src/schema.rs
- tesseract-server/Cargo.toml
- tesseract-server/src/app.rs
- tesseract-server/src/handlers/logic_layer/aggregate.rs
- tesseract-server/src/handlers/logic_layer/geoservice.rs
- tesseract-server/src/handlers/logic_layer/mod.rs
- tesseract-server/src/main.rs
> Geoservice support

- tesseract-core/src/schema.rs
- tesseract-core/src/schema/json.rs
- tesseract-core/src/schema/metadata.rs
- tesseract-core/src/schema/xml.rs
@frabarz adding you on as a reviewer because I wanted to ask some questions. Mainly, to confirm whether you want the structure of `standard` and `error` to be the same; then I'll add a field like `units` or something.
> [core] first pass on measuretype

- tesseract-core/src/lib.rs
- tesseract-core/src/schema.rs
- tesseract-core/src/schema/json.rs
- tesseract-core/src/schema/xml.rs
- tesseract-server/src/app.rs
- tesseract-server/src/handlers/logic_layer/aggregate.rs
- tesseract-server/src/handlers/logic_layer/metadata.rs
- tesseract-server/src/handlers/logic_layer/mod.rs
- tesseract-server/src/handlers/metadata.rs
- tesseract-server/src/handlers/mod.rs
- tesseract-server/src/logic_layer/config.rs
> Members locale enpoint

- tesseract-server/src/logic_layer/cache.rs
minor tweak for reducing some duplication while building certain cache query strings
> tweaks string formatting for cache query strings

- .travis.yml
- README.md
- tesseract-clickhouse/src/sql/aggregator.rs
> Add Basic Travis CI integration

- Cargo.lock
- tesseract-clickhouse/Cargo.toml
- tesseract-server/Cargo.toml
Updates clickhouse driver version, which fixes some bugs in the driver and also adds support for a client timeout feature.
> upgrades clickhouse driver version

- tesseract-server/src/handlers/metadata.rs
Should be able to return the schema even without Logic Layer
> Fixes the issue of logic layer error

- tesseract-core/src/format.rs
- tesseract-core/src/schema/metadata.rs
- tesseract-server/src/handlers/aggregate.rs
- tesseract-server/src/handlers/logic_layer/aggregate.rs
- tesseract-server/src/handlers/logic_layer/metadata.rs
- tesseract-server/src/handlers/logic_layer/relations.rs
- tesseract-server/src/handlers/metadata.rs
- tesseract-server/src/handlers/util.rs
Adds support for the Source Annotation Payload
> Source annotations #224

- tesseract-core/src/lib.rs
Solves the issue of ordering by RCA
closes #220
> Ordering by RCA issue #220

- tesseract-server/src/handlers/logic_layer/aggregate.rs
Adds support to get the locale names of the levels in RCA using the logic layer
> Locale name of levels  in RCA Solves the issue #229 

- tesseract-server/src/handlers/logic_layer/aggregate.rs
> Fix for logic layer string measures

- .travis.yml
- Cargo.lock
- docker-compose.yml
- docker/scripts/init_db.sh
- tesseract-clickhouse/tests/integration.rs
- tesseract-server/src/lib.rs
- tesseract-server/src/logic_layer/config.rs
- tesseract-server/src/logic_layer/mod.rs
- tesseract-server/src/schema_config.rs
- tests/Cargo.toml
- tests/src/clickhouse_end_to_end.rs
- tests/src/query_ir.rs
* adds a first pass at end to end testing (including schema, logic layer and logic layer API call)
> Initial end-to-end test

- tesseract-server/src/app.rs
> adds Vary header to server responses

- tesseract-clickhouse/src/df.rs
- tesseract-clickhouse/src/sql.rs
- tesseract-clickhouse/src/sql/options.rs
- tesseract-clickhouse/src/sql/rate.rs
- tesseract-core/src/format_stream.rs
- tesseract-core/src/lib.rs
- tesseract-core/src/query.rs
- tesseract-core/src/query_ir.rs
- tesseract-server/README.md
- tesseract-server/src/handlers/aggregate.rs
- tesseract-server/src/handlers/logic_layer/aggregate.rs
- tesseract-server/src/handlers/logic_layer/relations.rs
- tesseract-server/src/logic_layer/README.md
1) Added Support to perform filters query from Logic Layer.
2) Fixed the sorting bug on the measure used in RCA.
3) Adds support to perform multiple filters operations(i.e. filters=measure1.comparison1.value1, measure2.comparison2.value2).
> Logic Layer improvements

- Cargo.lock
- tesseract-clickhouse/Cargo.toml
- tesseract-server/src/handlers/diagnosis.rs
> Add diagnosis check for unique ids

- tesseract-clickhouse/src/sql/primary_agg.rs
* Proposed quick fix for #280
* A few proposed code cleanup edits
> Fix for clickhouse SQL joined subquery error

- tesseract-server/src/auth.rs
- tesseract-server/src/handlers/diagnosis.rs
This PR is just an extension of the old functionality so we can diagnose all cubes in the same query.
> Diagnosing all cubes

- Cargo.lock
- tesseract-server/Cargo.toml
- tesseract-server/src/app.rs
- tesseract-server/src/handlers/aggregate.rs
- tesseract-server/src/handlers/diagnosis.rs
- tesseract-server/src/handlers/logic_layer/aggregate.rs
- tesseract-server/src/handlers/util.rs
- tesseract-server/src/main.rs
- tests/src/clickhouse_end_to_end.rs
> Redis cache
