justfile, moe.md, tesseract-clickhouse/src/lib.rs, tesseract-clickhouse/src/sql.rs, tesseract-clickhouse/src/sql/aggregator.rs, tesseract-clickhouse/src/sql/growth.rs, tesseract-clickhouse/src/sql/primary_agg.rs, tesseract-clickhouse/src/sql/rca.rs, tesseract-core/src/lib.rs, tesseract-core/src/query_ir.rs, tesseract-core/src/schema.rs, tesseract-core/src/schema/aggregator.rs, tesseract-core/src/schema/json.rs, tesseract-core/src/schema/xml.rs, tesseract-core/src/sql.rs, tesseract-server/src/main.rs, weighted_avg.md
Implements moe and weighted avg
Has some reworking of how aggregations are passed through subqueries. Basically, for moe and weighted avg, only sum(col) can be performed on the fact scan, and then the whole formula can be applied after joining with the dim tables and rolling up on parent levels.
Handling of aggregation sql generation put into own module, and has some tests.
=> Feature/aggregations: moe and weighted avg

tesseract-clickhouse/src/sql.rs, tesseract-clickhouse/src/sql/cuts.rs, tesseract-clickhouse/src/sql/primary_agg.rs, tesseract-core/src/lib.rs, tesseract-core/src/names.rs, tesseract-core/src/query_ir.rs
The first phase of searching in cuts is a little limited:
- the switch applies to all members in a dimension:
cuts[]=*Geography.State.State.Cali,Ark
- matching happens using '%xxxxx%'
- when using this search match, it always happens on labels if
available, fallback to key if not.
So, you can't specify per member whether it's:
- NOT
- prefix/postfix/any matching
- on key or label
=> [core][clickhouse] Implement first phase search in cut

tesseract-server/src/handlers/logic_layer/aggregate.rs, tesseract-server/src/handlers/logic_layer/shared.rs, tesseract-server/src/logic_layer/cache.rs, tesseract-server/src/logic_layer/config.rs, tesseract-server/src/main.rs
Proposed config syntax:
```json
{
"aliases": {
"cubes": [
{
"name": "Sales",
"alternatives": ["sales", "sale"]
}
]
},
"name_sets": [
{
"level_name": "Category",
"sets": [
{
"set_name": "Set 1",
"values": ["Books", "Videos"]
},
{
"set_name": "Set 2",
"values": ["Sports", "Various"]
}
]
}
]
}
```
=> [logic layer] Name sets support

tesseract-core/src/lib.rs, tesseract-server/src/app.rs, tesseract-server/src/handlers/aggregate_stream.rs, tesseract-server/src/handlers/logic_layer/mod.rs, tesseract-server/src/handlers/mod.rs, tesseract-server/src/main.rs, tesseract-server/src/schema_config.rs
Previously, for the sake of the logic layer, we had allowed only unique
level names in the schema.
Now, because we want to be able to have non-unique levels in the raw
schema, we just do a runtime check which changes what routes are loaded.
If unique levels, then regular logic layer is loaded.
If not unique levels, then a route which always returns 500 is loaded
for logic layer.
In the future, the LL will have aliases in the config to allow a
combination of LL and raw schema to have unique levels.
=> allow non-unique level names

tesseract-core/src/query.rs, tesseract-core/src/schema.rs, tesseract-server/src/handlers/logic_layer/aggregate.rs, tesseract-server/src/handlers/logic_layer/shared.rs, tesseract-server/src/logic_layer/cache.rs, tesseract-server/src/logic_layer/config.rs, tesseract-server/src/logic_layer/mod.rs, tesseract-server/src/main.rs
Example configuration, assuming there is a `[Category].[Category].[Category]` level and a `[Category].[Category].[Category].[Name]` property:
```json
"aliases": {
"cubes": [
{
"name": "Sales",
"alternatives": ["sales", "sale"],
"levels": [
{
"current_name": "Category 2.Category 2.Category",
"unique_name": "Category 2"
}
],
"properties": [
{
"current_name": "Category 2.Category 2.Category.Name",
"unique_name": "Name 2"
}
]
}
]
}
```
=> [logic layer] Adds name substitutions to logic layer config

tesseract-server/src/app.rs
PR to allow the API to accept URLs like `/cubes/` instead of just `/cubes` (right now `/cubes/` will give a 404).
=> allow the api to accept urls with trailing slashes

tesseract-clickhouse/src/lib.rs, tesseract-clickhouse/src/sql.rs, tesseract-clickhouse/src/sql/primary_agg.rs, tesseract-clickhouse/src/sql/rate.rs, tesseract-clickhouse/src/sql/rca.rs, tesseract-core/src/lib.rs, tesseract-core/src/query.rs, tesseract-core/src/query_ir.rs, tesseract-core/src/schema/aggregator.rs, tesseract-server/src/handlers/aggregate.rs, tesseract-server/src/handlers/logic_layer/shared.rs
This first version only allows 1 measure defined when a rate param is received. That measure is required to have either a sum or count aggregator and is used to calculate the rate.
Other than that, the raw Tesseract syntax is `rate=Dim.Hier.Level.val_1` and the logic layer syntax is `rate=Level.val_1`.
Multiple values can be passed in separated by commas: `rate=Level.val_1,val_2`.
For now, at least, we'll allow drilldowns and cuts on the level used for the rate calculation. Drilldowns will always result in a rate of 1. Cuts allow for rate calculation in a subset of the level universe (for example, calculating the rate of "Non-fiction" sales inside a "Books" named set.
=> Rate calculation

tesseract-core/src/lib.rs
Currently, when a tesseract user has a dimension with multiple hierarchies and doesn't specify a default, the error doesn't say where the issue is happening. So this PR adds a little extra info to make it easier to track down.
(Not crazy about the extra `cube_name = &cube.name` but was the easiest interim fix for working around double borrowing issue inside closure -- so feel free to suggest alternatives)
=> adds cube and dimension name to default hierarchy error message

tesseract-core/src/lib.rs, tesseract-core/src/query.rs, tesseract-core/src/schema.rs, tesseract-core/src/schema/json.rs, tesseract-core/src/schema/xml.rs, tesseract-server/src/handlers/aggregate.rs, tesseract-server/src/handlers/logic_layer/shared.rs
The goal of this feature is to handle certain cases in data sets where "Total" rows may exist alongside other disaggregate values.
e.g.  assuming a data table `dm_test` that looked like
|Year|Race|Value|
|--|--|--|
|2017|Total|11|  
|2017|A|5|
|2017|B|5|  
The following XML would allow the definition of a default_member
```xml
<Cube name="DM">
<Table name="dm_test"/>
<Dimension foreign_key="year" name="Year">
<Hierarchy name="Year" primary_key="year">
<Level name="Year" key_column="year" />
</Hierarchy>
</Dimension>
<Dimension foreign_key="race" name="Race">
<Hierarchy name="Race" primary_key="race" default_member="Race.Race.Race.Total">
<Level name="Race" key_column="race" key_type="text"/>
</Hierarchy>
</Dimension>
<Measure name="Value" column="value" aggregator="sum" />
</Cube>
``` …
=> Adds new default member feature for hierarchies

tesseract-core/src/lib.rs
Not ideal, but just wanted to push this patch for now to fix an issue that causes drilldowns to fail when certain dimensions do not have a specified default member. This is meant as a break/fix patch and will take a look at reverting back to a better Vec<Cut> construction (possibly using foreach instead of map).
=> Fixes bug with dimensions without default members

tesseract-clickhouse/src/lib.rs, tesseract-clickhouse/src/sql.rs, tesseract-clickhouse/src/sql/options.rs, tesseract-core/src/lib.rs, tesseract-core/src/query.rs, tesseract-core/src/query_ir.rs, tesseract-server/src/handlers/aggregate.rs, tesseract-server/src/handlers/logic_layer/shared.rs
This is one potential avenue for supporting the sparse feature so that users can filter rows where all measures are null. 
Example usage:
`http://localhost:7777/data?cube=DM&drilldowns=Race&measures=Value&sparse=true`
I think another way to implement this would be to tap into the existing `query_ir.filters` functionality. One challenge there is that at the moment it looks like the comparisons/constraints structs are not generalized beyond integer operations (as `n` is an `i64`) , additionally the `sql_string` for constraints will likely need to be driver specific (i.e clickhouse uses `isNotNull(x)` versus Postgres' `x IS NOT NULL`. Down the road if/when those elements are refactored the sparse functionality could be updated accordingly, but I think this logic should do the job for now.
As …
=> Adds sparse feature to support filtering rows where all measures are null

tesseract-clickhouse/src/sql/aggregator.rs, tesseract-core/src/schema/aggregator.rs, tesseract-core/src/schema/metadata.rs, tesseract-core/src/sql.rs
Two aggregators for `max` and `min` have been added by extending code on four files. When running `cargo build` the operation has been successful.
=> Added max and min aggregators

tesseract-server/pkg/deb/maintainer-scripts/postinst
Had some questions about the best way to handle this, so let me know what you think.
Basically, I just need to be able to upgrade without changing the .service file.
on the post install, I'm just skipping all the customizing of the file.
And for copying of the .service in the firs place, it should be blocked by https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles
=> [server, pkg] early exit on dpkg postscript if upgrading

tesseract-core/src/lib.rs, tesseract-server/src/app.rs, tesseract-server/src/errors.rs, tesseract-server/src/handlers/logic_layer/mod.rs, tesseract-server/src/logic_layer/config.rs, tesseract-server/src/main.rs
- updates methods for checking if level and property names are unique, by returning cube and name info if not. This uses a new enum.
- plumbs this data into the Actix app state.
- accesses this data in the handlers if names are not unique, and sends out the detailed message if `--debug` is set. Otherwise, keeps the current `555` error code.
closes #184
=> [server] LL duplicate names error message

Cargo.lock, Cargo.toml, tesseract-server/Cargo.toml, tesseract-server/src/app.rs, tesseract-server/src/auth.rs, tesseract-server/src/handlers/util.rs, tesseract-server/src/lib.rs, tesseract-server/src/main.rs, tests/src/clickhouse_end_to_end.rs
First pass at JWT webtoken support. This PR leaves in place the existing API key mechanism and adds a new JWT token based mechanism. At the moment this approach uses middleware to apply authorization to all routes uniformly (and does not currently distinguish between public/private cubes). API expects a valid token passed as `x-tesseract-jwt-token` and with claim of `status=valid` (hard-coded, for now though could also be configurable in the future).
=> adds initial support for JWT webtoken based authorization

.travis.yml, tesseract-core/src/lib.rs, tesseract-core/src/schema.rs, tesseract-core/src/schema/json.rs, tesseract-core/src/schema/metadata.rs, tesseract-core/src/schema/xml.rs, tesseract-server/src/auth.rs, tesseract-server/src/handlers/metadata.rs, tesseract-server/src/handlers/util.rs, tesseract-server/src/main.rs
* Users can now give cubes a `minAuthLevel` value. This will require that tokens must have at least that level or higher in the `auth_level` claim of their token. By default valid users without an explicit auth level will have an auth level of 0, and also cubes will have a default auth level of 0.
* The `/cubes` endpoint listing will now filter out cubes that a user does not have access to.
=> Adds finer grained JWT access control

tesseract-server/src/logic_layer/cache.rs
This PR adds support for `time=time.latest` cuts for cubes with time-depth other than `year`.
=> Fix for time cuts

tesseract-server/src/handlers/logic_layer/aggregate.rs, tesseract-server/src/handlers/logic_layer/relations.rs, tesseract-server/src/logic_layer/cache.rs
We noticed that [this query](https://api.oec.world/tesseract/relations.jsonrecords?cube=patents_i_uspto_w_cpc&Subclass=H01Q:parents) was taking forever to return results. Upon closer inspection, we were doing an unnecessary clone that is now removed.
=> Faster CubeCache return

tesseract-core/src/lib.rs, tesseract-server/src/handlers/aggregate.rs, tesseract-server/src/handlers/aggregate_stream.rs, tesseract-server/src/handlers/logic_layer/aggregate.rs, tesseract-server/src/logic_layer/config.rs
Right now unique level names are not being returned as the header in the response: https://api.oec.world/tesseract/data.jsonrecords?cube=trade_i_baci_a_92&drilldowns=Exporter+Continent%2CImporter+Continent&measures=Trade+Value&parents=false&sparse=false
This PR fixes that by substituting the header names for the unique version whenever there are multiple headers with the same name.
Sample response from the same query:
=> Adds unique header names when appropriate

tesseract-core/src/lib.rs, tesseract-server/src/app.rs, tesseract-server/src/auth.rs, tesseract-server/src/handlers/aggregate.rs, tesseract-server/src/handlers/aggregate_stream.rs, tesseract-server/src/handlers/diagnosis.rs, tesseract-server/src/handlers/logic_layer/aggregate.rs, tesseract-server/src/handlers/logic_layer/metadata.rs, tesseract-server/src/handlers/logic_layer/relations.rs, tesseract-server/src/handlers/metadata.rs, tesseract-server/src/handlers/util.rs, tesseract-server/src/main.rs, tests/src/clickhouse_end_to_end.rs
* removes old API key verification.
* reworks JWT auth to allow access by default. (All requests will be considered to have an `auth_level` of 0)
=> Authorization refactor

tesseract-clickhouse/src/sql/growth.rs
By default, return a growth of NULL instead of 0 if no previous data available
=> returns null growth by default instead of 0

tesseract-server/src/handlers/logic_layer/aggregate.rs
Adds support for a new "exclude" param like this: `exclude=Subnat+Geography:48,49;Trade+Flow:1`. 
Excluding multiple levels is also supported, as long as they are separated by a `;` as in the example above. Since this is the logic layer, unique level names are expected.
=> Logic Layer support for "exclude"

Dockerfile
- Modify Dockerfile to install `openssl ca-certificates wget and curl` for clickhouse-server secure connection driver
=> reqlibraries on dfile for ch-db secure connection
